#!/bin/bash

chunkc=/usr/local/bin/chunkc

active=$($chunkc tiling::query -d id)
total=$($chunkc tiling::query -D 1)
mode=$($chunkc tiling::query -d mode)

echo "$mode@$active@$total@$(/usr/local/bin/python3 ./nerdbar.widget/scripts/activeWindow.py)"